class Buttons:
    back = '⬅ Back'
    introduction_tutor = 'I am a tutor 🍎'
    introduction_client = 'I am a student 🤓'
    support = '⚠ Support ⚠'
    new_order = '✨New order✨'
    my_chats_client = '💬My chats💬'
    my_chats_tutor = '💬 My chats 💬'

    subjects = 'Math', 'Stats', 'Finance', 'Business', 'Chem'
    level = 'Level 1', 'Level 2', 'Level 3'
    q_type = 'Short answers', 'Multiple choice questions', 'Both types'
    timed = 'Yes', 'No'
    done = 'DONE'
    accept = 'ACCEPT'
